# Generated by Django 3.0.6 on 2020-12-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='会议年份')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=20, verbose_name='会议类型')),
            ],
            options={
                'verbose_name': '年度会议登记本',
                'verbose_name_plural': '年度会议登记本',
                'db_table': 'annual_meeting',
            },
        ),
        migrations.CreateModel(
            name='ShareholderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdxm', models.CharField(max_length=20)),
                ('gdtype', models.CharField(max_length=20)),
                ('gddmk', models.CharField(max_length=15)),
                ('sfz', models.CharField(max_length=15)),
                ('rs', models.SmallIntegerField()),
                ('frA', models.IntegerField()),
                ('gzA', models.IntegerField()),
                ('gzB', models.IntegerField()),
                ('dlr', models.CharField(max_length=10)),
                ('meno', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '股东信息花名册',
                'verbose_name_plural': '股东信息花名册',
                'db_table': 'gdbook',
            },
        ),
        migrations.CreateModel(
            name='OnSiteMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cx', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否出席')),
                ('xcorwl', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], verbose_name='是否出席现场')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Meeting')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.ShareholderInfo')),
            ],
            options={
                'verbose_name': '现场会议登记表',
                'verbose_name_plural': '现场会议登记表',
                'db_table': 'on_site_meeting',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(through='apps.OnSiteMeeting', to='apps.ShareholderInfo'),
        ),
    ]
