# Generated by Django 3.0.6 on 2020-12-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='current_year',
            field=models.BooleanField(default=False),
        ),
    ]
