# Generated by Django 3.0.6 on 2020-12-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_meeting_current_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholderinfo',
            name='sfz',
            field=models.CharField(max_length=25),
        ),
    ]
