# Generated by Django 3.0.6 on 2020-12-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20201215_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsitemeeting',
            name='cx',
            field=models.BooleanField(default=False, verbose_name='是否出席'),
        ),
        migrations.AlterField(
            model_name='onsitemeeting',
            name='xcorwl',
            field=models.BooleanField(default=False, verbose_name='是否出席现场'),
        ),
    ]
