# Generated by Django 3.0.6 on 2020-12-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20201215_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='year',
            field=models.SmallIntegerField(verbose_name='会议年份'),
        ),
    ]
