# Generated by Django 3.0.6 on 2020-12-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20201216_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='motion',
            field=models.CharField(default="''", max_length=80, verbose_name='议案主题'),
        ),
    ]
