# Generated by Django 3.0.6 on 2020-12-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_meeting_motion'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='addrress',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='motion',
            field=models.CharField(default='', max_length=100, verbose_name='议案主题'),
        ),
    ]
