# Generated by Django 3.0.6 on 2021-01-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20210118_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsitemeeting',
            name='meno',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
