# Generated by Django 3.0.6 on 2021-01-19 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_onsitemeeting_meno'),
    ]

    operations = [
        migrations.CreateModel(
            name='GB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='会议年份')),
                ('gb', models.IntegerField()),
                ('ltag', models.IntegerField()),
                ('ltbg', models.IntegerField()),
                ('fltg', models.IntegerField()),
            ],
            options={
                'verbose_name': '股本信息表',
                'verbose_name_plural': '股本信息表',
                'db_table': 'gb',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='gb_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.GB'),
        ),
    ]
