# Generated by Django 3.0.6 on 2021-01-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20210121_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholderinfo',
            name='gddmk',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shareholderinfo',
            name='rs',
            field=models.SmallIntegerField(null=True),
        ),
    ]
