# Generated by Django 3.0.6 on 2021-02-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20210121_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='议案主题')),
                ('fanduiA', models.IntegerField()),
                ('fanduiB', models.IntegerField()),
                ('qiquanA', models.IntegerField()),
                ('qiquanB', models.IntegerField()),
                ('is_huibi', models.BooleanField(default=False)),
                ('huibiA', models.IntegerField()),
                ('huibiB', models.IntegerField()),
                ('annual_meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.Meeting')),
            ],
            options={
                'verbose_name': '议案信息表',
                'verbose_name_plural': '议案信息表',
                'db_table': 'motion_book',
            },
        ),
    ]
