# Generated by Django 3.0.6 on 2021-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_motionbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionbook',
            name='name',
            field=models.CharField(max_length=80, verbose_name='议案主题'),
        ),
    ]
