# Generated by Django 3.0.6 on 2021-02-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20210204_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionbook',
            name='fanduiA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motionbook',
            name='fanduiB',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motionbook',
            name='huibiA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motionbook',
            name='huibiB',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motionbook',
            name='qiquanA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motionbook',
            name='qiquanB',
            field=models.IntegerField(null=True),
        ),
    ]
