# Generated by Django 3.0.6 on 2021-02-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_auto_20210204_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionbook',
            name='is_huibi',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
