# Generated by Django 3.0.6 on 2021-02-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20210204_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccumulateMition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='议案主题')),
                ('zancheng', models.IntegerField(null=True)),
                ('annual_meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.Meeting')),
            ],
            options={
                'verbose_name': '议案信息表',
                'verbose_name_plural': '议案信息表',
                'db_table': 'accumulate_book',
            },
        ),
    ]
