# Generated by Django 3.0.6 on 2021-02-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_accumulatemition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccumulateMition',
            new_name='AccumulateMotion',
        ),
    ]
