# Generated by Django 3.0.6 on 2021-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_auto_20210204_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionbook',
            name='zanchengA',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='motionbook',
            name='zanchengB',
            field=models.IntegerField(null=True),
        ),
    ]
