# Generated by Django 3.0.6 on 2021-02-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_auto_20210207_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accumulatemotion',
            old_name='zancheng',
            new_name='zanchengA',
        ),
        migrations.AddField(
            model_name='accumulatemotion',
            name='is_tongji',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='accumulatemotion',
            name='zanchengB',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='motionbook',
            name='is_tongji',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
