# Generated by Django 3.0.6 on 2021-02-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_auto_20210210_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='is_tongji',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
