# Generated by Django 3.0.6 on 2021-02-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_auto_20210210_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='is_tongji',
            new_name='has_tongji',
        ),
    ]
