# Generated by Django 3.0.6 on 2021-02-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_auto_20210210_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='has_tongji',
        ),
    ]
