# Generated by Django 3.0.6 on 2021-02-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_meeting_is_tongji'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='desc',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
