# Generated by Django 3.0.6 on 2021-02-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_meeting_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='desc',
            new_name='descr',
        ),
    ]
