# Generated by Django 3.0.6 on 2021-02-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_auto_20210222_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionbook',
            name='descr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
