# Generated by Django 3.0.6 on 2021-03-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_motionbook_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsitemeeting',
            name='rs',
            field=models.IntegerField(default=1, verbose_name='人数'),
        ),
    ]
