# Generated by Django 3.0.6 on 2021-03-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_onsitemeeting_rs'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionbook',
            name='zxg_fanduiA',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='motionbook',
            name='zxg_fanduiB',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='motionbook',
            name='zxg_qiA',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='motionbook',
            name='zxg_qiB',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='motionbook',
            name='zxg_zanchengA',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='motionbook',
            name='zxg_zanchengB',
            field=models.IntegerField(null=True),
        ),
    ]
