# Generated by Django 3.0.6 on 2021-07-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_auto_20210301_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkVoteCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zancheng', models.IntegerField(null=True)),
                ('fandui', models.IntegerField(null=True)),
                ('qiquan', models.IntegerField(null=True)),
                ('motion_id', models.IntegerField(null=True)),
                ('equityType', models.SmallIntegerField(choices=[(0, 'A'), (1, 'B')])),
                ('excelName', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': '网络投票统计表',
                'verbose_name_plural': '网络投票统计表',
                'db_table': 'network_vote_count',
            },
        ),
    ]
