# Generated by Django 3.0.6 on 2021-07-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_auto_20210728_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholderinfo',
            name='gddmk',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
