# Generated by Django 3.0.6 on 2021-07-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_auto_20210728_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsitemeeting',
            name='huibi_descr',
        ),
        migrations.RemoveField(
            model_name='onsitemeeting',
            name='vote',
        ),
        migrations.CreateModel(
            name='VoteRecordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zanchengVote', models.IntegerField(null=True)),
                ('vote', models.SmallIntegerField(choices=[(1, '赞成'), (2, '反对'), (3, '弃权'), (4, '回避')], null=True)),
                ('equityType', models.SmallIntegerField(choices=[(0, 'A'), (1, 'B')])),
                ('huibi_descr', models.CharField(default=None, max_length=120, null=True)),
                ('motionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.MotionBook')),
            ],
            options={
                'verbose_name': '投票记录统计表',
                'verbose_name_plural': '投票记录统计表',
                'db_table': 'vote_record_detail',
            },
        ),
    ]
