# Generated by Django 3.0.6 on 2021-07-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_auto_20210728_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterecorddetail',
            name='gdId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.ShareholderInfo'),
            preserve_default=False,
        ),
    ]
