# Generated by Django 3.0.6 on 2021-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_auto_20210729_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionbook',
            name='sharehold',
            field=models.ManyToManyField(through='apps.VoteRecordDetail', to='apps.ShareholderInfo'),
        ),
    ]
