# Generated by Django 3.0.6 on 2021-08-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_motionbook_sharehold'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionbook',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.MotionBook'),
        ),
    ]
