# Generated by Django 3.0.6 on 2021-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_motionbook_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionbook',
            name='isCumulated',
            field=models.BooleanField(null=True),
        ),
    ]
