# Generated by Django 3.0.6 on 2021-08-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_motionbook_iscumulated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionbook',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.MotionBook'),
        ),
    ]
